# Generated by Django 2.1.1 on 2018-10-16 09:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_auto_20181016_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gifts',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gift_name', models.CharField(max_length=100, null=True)),
                ('descr', models.CharField(max_length=200, null=True)),
                ('price', models.FloatField(default=0, null=True)),
                ('store', models.SmallIntegerField(default=1, null=True)),
                ('clicknum', models.IntegerField(default=0, null=True)),
                ('grounding', models.FloatField(null=True)),
                ('brand', models.CharField(max_length=32, null=True)),
                ('remark', models.CharField(max_length=64, null=True)),
                ('giftId', models.CharField(max_length=64, null=True)),
                ('field02', models.CharField(max_length=64, null=True)),
                ('field03', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsCart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cart_num', models.SmallIntegerField(default=1)),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GiftsCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GiftsOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_num', models.SmallIntegerField(default=1)),
                ('ordertime', models.IntegerField()),
                ('note', models.CharField(max_length=200, null=True)),
                ('field01', models.CharField(max_length=64, null=True)),
                ('field02', models.CharField(max_length=64, null=True)),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
            ],
        ),
        migrations.CreateModel(
            name='GiftsPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pic_url', models.CharField(max_length=100, null=True)),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
            ],
        ),
        migrations.CreateModel(
            name='GiftsRecord',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_num', models.SmallIntegerField(default=1)),
                ('record_date', models.IntegerField()),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GiftsThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_status', models.SmallIntegerField(choices=[(0, '未点赞'), (1, '点赞')])),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='GiftsType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('typename', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='OrderStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ststus_name', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='giftsorder',
            name='status',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.OrderStatus'),
        ),
        migrations.AddField(
            model_name='giftsorder',
            name='userinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
        migrations.AddField(
            model_name='gifts',
            name='type_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.GiftsType'),
        ),
    ]
