# Generated by Django 2.1.1 on 2018-10-18 00:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181016_1516'),
        ('gift', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftsComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GiftsFestival',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dayname', models.CharField(max_length=64, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='gifts',
            name='brand',
        ),
        migrations.AddField(
            model_name='giftscomment',
            name='gifts',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts'),
        ),
        migrations.AddField(
            model_name='giftscomment',
            name='userinfo',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
