# Generated by Django 2.1.1 on 2018-10-18 03:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0003_gifts_day_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gifts',
            old_name='field02',
            new_name='giftImg',
        ),
    ]
