# Generated by Django 2.1.1 on 2018-10-19 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0006_auto_20181019_1504'),
    ]

    operations = [
        migrations.AddField(
            model_name='gifts',
            name='new_price',
            field=models.FloatField(default=0),
        ),
    ]
