# Generated by Django 2.1.1 on 2018-10-20 02:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0008_gifts_gift_material'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gifts',
            name='gift_material',
        ),
    ]
