# Generated by Django 2.1.1 on 2018-10-20 09:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0009_remove_gifts_gift_material'),
    ]

    operations = [
        migrations.CreateModel(
            name='GiftsDetailPic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img_url', models.CharField(max_length=100, null=True)),
                ('gifts', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='gift.Gifts')),
            ],
        ),
    ]
