# Generated by Django 2.1.1 on 2018-10-20 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0012_remove_giftsdetailpic_img_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GiftsDetailPic',
        ),
    ]
