# Generated by Django 2.1.1 on 2018-10-22 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0017_remove_giftsorder_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='giftsorder',
            name='ordertime',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='giftsrecord',
            name='record_date',
            field=models.FloatField(),
        ),
    ]
