# Generated by Django 2.1.1 on 2018-10-22 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gift', '0018_auto_20181022_0943'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gifts',
            name='giftImg',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
