# Generated by Django 2.1.1 on 2018-10-18 13:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181016_1516'),
        ('post', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PostCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='PostThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_status', models.SmallIntegerField(choices=[(0, '未点赞'), (1, '点赞')])),
                ('post_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='post.Post')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
