# Generated by Django 2.1.1 on 2018-10-23 01:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_auto_20181019_1605'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='postthumb',
            name='thumb_status',
        ),
    ]
