# Generated by Django 2.1.1 on 2018-10-18 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('user', '0013_auto_20181016_1516'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tribune',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ttitle', models.CharField(max_length=32)),
                ('ttitleimg', models.CharField(max_length=200, null=True)),
                ('tdetailcont', models.CharField(max_length=9000)),
                ('tbriefcont', models.CharField(max_length=900)),
                ('t_createtime', models.IntegerField()),
                ('t_userid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TribuneCollect',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tribune_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribune.Tribune')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TribuneReply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tReply_con', models.CharField(max_length=120)),
                ('tReply_time', models.IntegerField()),
                ('tReply_pid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribune.Tribune')),
                ('tReply_uid', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
        migrations.CreateModel(
            name='TribuneThumb',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('thumb_status', models.SmallIntegerField(choices=[(0, '未点赞'), (1, '点赞')])),
                ('tribune_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tribune.Tribune')),
                ('userinfo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo')),
            ],
        ),
    ]
