# Generated by Django 2.1.1 on 2018-10-24 04:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tribune', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tribunethumb',
            name='thumb_status',
        ),
    ]
