# Generated by Django 2.1.1 on 2018-10-08 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='apply',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('inviter', models.SmallIntegerField()),
                ('binviter', models.SmallIntegerField()),
                ('apply_time', models.DateTimeField(auto_now_add=True)),
                ('replay', models.DateTimeField(auto_now_add=True)),
                ('field01', models.CharField(max_length=64, null=True)),
                ('field02', models.CharField(max_length=64, null=True)),
                ('field03', models.CharField(max_length=64, null=True)),
            ],
        ),
    ]
