# Generated by Django 2.1.1 on 2018-10-16 08:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vein', '0006_auto_20181009_1647'),
    ]

    operations = [
        migrations.AlterField(
            model_name='apply',
            name='replay',
            field=models.IntegerField(null=True),
        ),
    ]
