# Generated by Django 2.1.1 on 2018-10-08 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=32, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=64, unique=True)),
                ('email', models.CharField(max_length=64, null=True, unique=True)),
                ('password', models.CharField(max_length=64)),
                ('pub_time', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
