# Generated by Django 2.1.1 on 2018-10-08 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_role_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gender',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sexname', models.CharField(max_length=16, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nickname', models.CharField(max_length=64, null=True)),
                ('birthday', models.DateField()),
                ('signature', models.CharField(max_length=200, null=True)),
                ('location', models.CharField(max_length=32, null=True)),
                ('username', models.CharField(max_length=32, null=True)),
                ('qq', models.CharField(max_length=32, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='role',
            old_name='name',
            new_name='rolename',
        ),
    ]
