# Generated by Django 2.1.1 on 2018-10-08 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20181008_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Integral',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('integral_num', models.SmallIntegerField(default=0, null=True)),
            ],
        ),
    ]
