# Generated by Django 2.1.1 on 2018-10-08 13:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_integral'),
    ]

    operations = [
        migrations.AddField(
            model_name='integral',
            name='userinfo_id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='user.UserInfo'),
        ),
    ]
