# Generated by Django 2.1.1 on 2018-10-08 15:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20181008_2327'),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('receiver', models.CharField(max_length=16)),
                ('province', models.CharField(max_length=16)),
                ('city', models.CharField(max_length=16)),
                ('area', models.CharField(blank=True, max_length=16, null=True)),
                ('detailLocation', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=32)),
                ('postcode', models.CharField(blank=True, max_length=16, null=True)),
            ],
        ),
    ]
