# Generated by Django 2.1.1 on 2018-10-09 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_address_user_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_time',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.IntegerField(),
        ),
    ]
