# Generated by Django 2.1.1 on 2018-10-16 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_auto_20181009_1608'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gender',
            name='sexname',
            field=models.CharField(max_length=16, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pub_time',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.IntegerField(null=True),
        ),
    ]
