# Generated by Django 2.1.1 on 2018-10-21 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20181016_1516'),
    ]

    operations = [
        migrations.AddField(
            model_name='address',
            name='status',
            field=models.SmallIntegerField(default=1),
        ),
    ]
