# Generated by Django 2.1.1 on 2018-10-22 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_address_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='pub_time',
            field=models.FloatField(null=True),
        ),
    ]
