# Generated by Django 2.1.1 on 2018-10-24 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_auto_20181023_1422'),
    ]

    operations = [
        migrations.CreateModel(
            name='Register',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telephone', models.CharField(max_length=11)),
                ('time', models.DateTimeField()),
                ('message_code', models.CharField(max_length=8)),
            ],
        ),
    ]
