# Generated by Django 2.1.1 on 2018-10-24 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_register'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userinfo',
            name='birthday',
            field=models.FloatField(null=True),
        ),
    ]
